### ISSUE TITLE
Please consider the language settings.

### ISSUE THREAD

**Issue by creator-hian** [shrddr/shrddr.github.io#11]
Hello. Your help is always greatly appreciated.

Your role is very significant in Korea as well, and I have thought of a way to better approach Korean people about this. Currently, the language setting is only supported in English and Russian. I would like to help, if possible, to provide Korean support.

One possible way is to help convert individual words on Korean servers. Is there any way to do this?

**Comment by shrddr** [comment]
do you mean item and node names need to be translated or the wording of the website itself as well (words like Empire, Total CP, Send, Config)?

**Comment by creator-hian** [comment]
I apologize for only now seeing the response. 
I believe it is sufficient to provide translations only for the Node, Item
