### ISSUE TITLE
Request of a Feature of CP optimizer housecraft

### ISSUE THREAD

**Issue by donyonyon** [shrddr/shrddr.github.io#13]
Hello , im a fan of your CP optimizer and workers empire, i dont know coding but i think my request is very easy for you.
I would want you to implement 2 more stats so i can see how much of the CP invested per lodging or slots or both is worth.
I mean something like this.

On the part of https://shrddr.github.io/workerman/housecraft.

1-Lodging per Cp  = workers hired / cp invested in lodging

2-Slots per CP = slots /  cp invested in slots

I want this in case u want  **more storage**  or worker (even if it doesnt work but u want to keep it there  or is on a workshop) on that city but u dont know whats the most profitable amount of slots or worker per cp used. 
It makes more sense on storage tho .

**In that case you would´nt use the building that it shows below.** on the https://shrddr.github.io/workerman/ that requests the minimum.

SO i can recalculate the total amount of CP that if have to use and put IN  :
📦 storage
23 worker items
+ 1 Seal + 1 Free slot

**_+ 0 _Personal items_ -----------------==== (PUT THERE the amount of slots i chose on the housecraft  - the required )
				        So i can see the buildings i really need ( note the minimum required) in the mainpage of workerman and 
                                        the CP is added to the total._**

- 16 initial
- 0 from P2W
= **9 required**

By the way it would be great to see when its using housecraft on both lodging and storage at the same time 
Separate in 3 other stats not only total CP used:
1- CP for lodging
2-Cp for storage
3-Total CP 

Thank you very much for your effort on doing this kind of things to make our game experience better.
Hope you can add this feature and 
Have a nice day.

**Comment by shrddr** [comment]
1 & 2 ok, 3 did not understand at all. if you mean storage calculation for workshops, that's in the TODO, not highest priority though

**Comment by donyonyon** [comment]
Thank you very much for this , i didnt expect u do reply and do it  so fast. 
U are a legend .
And u already did the number 3 it was simply the Total CP of slots+lodging.
Did a great job and i hope this may help others.

Keep working this way and u´ll get far.
Great job and thank you again.
