### ISSUE TITLE
Workers' houses, which can be taken when taking a workshop, are not taken into account

### ISSUE THREAD

**Issue by eroglu94** [shrddr/shrddr.github.io#15]
Example: 
Heidel 7-4 2. Floor (Costume Workshop)

While taking the specified workshop above, we can take lodging in 7-3 1F, but app doesn't understand it. I tried to manipulate it by increasing P2W lodging but it was unstable.

**Heidel Setup**
![image](https://github.com/shrddr/shrddr.github.io/assets/11258914/f828a371-d23b-409d-9ee0-54f7fc98c866)

**Heidel Config**
It says i should pick 8-1 and 4-1 worker homes but it is unnecessary since i already have took 7-3 1F (which gives 4 worker slots) because it was on our way already.
![image](https://github.com/shrddr/shrddr.github.io/assets/11258914/e45ae68e-565a-42d1-a8dd-8eee84899576)

**Heidel Manupulated P2W to observe unstable behaviour**
Increased P2W slots by 4 accepting that app completely ignored 7-3 1F.  But now It suggests to use 7-3 1F (Showing cost 5CP). So it means it is unaware that  7-3 1F is already taken to get Costume Workshop
![image](https://github.com/shrddr/shrddr.github.io/assets/11258914/a0465195-41ae-4dea-bccf-adf276064201)

**Workshop Config**
![image](https://github.com/shrddr/shrddr.github.io/assets/11258914/0c0582f9-7057-4f4b-87a6-7db835550a40)

This thing affects all setups. Because it calculates the lodging setup and CP usage wrong. It affects Best Untaken nodes and current nodes. Basically, you can't proceed further because all the data you see will be wrong from this point.

**Possible quick solution**
Option to allocate houses manually

Current worker list
[user (36).json](https://github.com/shrddr/shrddr.github.io/files/13324359/user.36.json)

**Comment by shrddr** [comment]
known issue, is in todo under "add lodgage support to workshop system"
