### ISSUE TITLE
Request for Adding Japanese Translation

### ISSUE THREAD

**Issue by MrKH-BDO** [shrddr/shrddr.github.io#18]
Hello shrddr and fellow project contributors,

We have a request to add Japanese translations for item names and node names in this project. Adding these translations would make the project more accessible and user-friendly for Japanese-speaking users.

Specifically, we would like to request translations for the following points:
- Item names
- Node names

If you have specific translation guidelines or style preferences for these items, please let us know, and we will follow those guidelines accordingly.

Adding Japanese translations would greatly benefit Japanese-speaking users and contributors. We appreciate your consideration of this request.

Thank you.

**Comment by shrddr** [comment]
English is available on Settings page
For Japanese drop me your languagedata.loc file from game/ads folder

**Comment by MrKH-BDO** [comment]
https://jpo-o-dn.playblackdesert.com/UploadData/ads/languagedata_jp/282/languagedata_jp.loc
Is this correct file?

**Comment by shrddr** [comment]
deploying, wait a minute and check

**Comment by MrKH-BDO** [comment]
I have confirmed that it has been translated into Japanese.

Thank you for the happiest black desert life!
