### ISSUE TITLE
Suboptimal node connection

### ISSUE THREAD

**Issue by AlexanderStanev** [shrddr/shrddr.github.io#19]
I've imported my empire and it looks like an additional unnecessary node connections were created at some places.

For example: 
I have invested in Costa Farm (with Heidel workers), Glish Ruins and Serendia Shrine (together with Southern Guard Camp). For some reason the Central Guard Camp is also considered taken, which is unnecessary and skews the efficiency rating of Serendia Shrine (since the Southern Guard Camp is also taken for Glish Ruins)

![image](https://github.com/shrddr/shrddr.github.io/assets/25152695/3f6d55a0-64b0-4b91-ae56-b3940b16dd8a)

Love the project, great work!

**Comment by shrddr** [comment]
as far as i understand this can only be solved by brute force which is unacceptable to keep responsive UI
but there's a workaround

> Q: Why are node connections so bad? When building path from town A to node B, it ignores the fact that there is already taken node C on the way.
A: Connections are resolved in same order the jobs were given. The worker who received the job first doesn't know yet about all others, and builds connection in a beeline. Each next worker sees and uses more and more connections made by previous workers in queue. You can push the worker at B to the end of queue by restarting his job. His connection will then be built last, with full knowledge of previous connections including the one that activated C.
