### ISSUE TITLE
A question about workerman

### ISSUE THREAD

**Issue by Leucothea** [shrddr/shrddr.github.io#2]
Thank you for the great work you do, it's really very helpful.

I have a question though, what is the exact meaning of the coefficient in front of the items (lucky drop)? What formula is used to calculate the final value of this coefficient? I tried to calculate it by changing the luck of the worker, but in the end I didn't find a good pattern.

I would be very grateful if you could tell me the detailed formula between the final value and the lucky drops coefficient.

Thanks again for your work!

Yours,

**Comment by shrddr** [comment]
In front of..? 
![IMG_20230614_002510](https://github.com/shrddr/shrddr.github.io/assets/899919/81a535f3-b45f-4d90-a776-0b5247ce9738)
This is average silver value of lucky cycle relative to average silver value of unlucky cycle. Just a QoL feature to see how important or not luck is on this node

**Comment by Leucothea** [comment]
I just want to know how does this value on the left in the attached image affect the final value and what is the exact formula?

[https://cdn.discordapp.com/attachments/420347151416164363/1118293604817965258/3.png](url)

Thank you!

**Comment by shrddr** [comment]
80050 in your image = (1-luck%)*average silver value of unlucky cycle + luck%* average silver value of lucky cycle
average silver value of unlucky cycle = Σ (dropcount * price) over all unlucky items
average silver value of lucky cycle = Σ (dropcount * price) over all lucky items

**Comment by Leucothea** [comment]
Thank you~! 👍

**Comment by shrddr** [comment]
- luck% = worker sheet luck + worker luck skills, nothing more
- nodes do not have luck in game, the [🍀4.26x] indicator is calculated from node drops and current market prices (or custom prices you entered)
- giant's bonus seems to work for all base mats like food and lumber, and at least one trace node
- however, after giant's bonus quantity is rounded down
1x1,684=1,684 rounded down to 1
2x1,684=3,368 rounded down to 3
3x1,684=5,052 rounded down to 5
- atm giant seems to bring same quantity of Archeologist's Sacks as goblin but more observations needed

**Comment by Leucothea** [comment]
I totally get it! Thank you very, very, very much indeed!
