### ISSUE TITLE
Request for Adding Taiwan Translation 

### ISSUE THREAD

**Issue by louyongjiu** [shrddr/shrddr.github.io#20]
Hello shrddr ,

We have a request to add Taiwan translations  in this project. Adding these translations would make the project more accessible and user-friendly for Taiwan users.

I have fork the project and make adjustments to use it normally.
But I have no project source code, I hope you can refer to my changes to make adjustments.
[https://github.com/louyongjiu/black-desert-worker/commit/a7a54fa852b234ba56a78139216bdd8d75f00662](url)
[https://github.com/louyongjiu/black-desert-worker/commit/4766821770bfa45fc712137409049db405aafe0d](url)

**Comment by shrddr** [comment]
woah, huge work here, but completely unnecessary, hope you at least had fun 😂
added TW now
