### ISSUE TITLE
Another question about the drops

### ISSUE THREAD

**Issue by Leucothea** [shrddr/shrddr.github.io#3]
Hi, excuse me, I have some new questions.

First, what distribution do the drops obey? Is it a chi-square distribution? Could you tell me the theoretical formula of the distribution model?

Also according to my observations, the giant's skill does not seem to work on all XXXX's sacks, not sure if I'm mistaken.

**Comment by shrddr** [comment]
binomial, for every item n rolls are made with p probability each, every success adds +1 quantity

**Comment by Leucothea** [comment]
But I found that the drops observed here(https://shrddr.github.io/workerman/droprates) is not symmetrical, for example, the maple timber drop expectation is 16.5, but the theoretical 16 and 17 drops are not same? (seems not binomial)

Also, due to the drops cannot be less than zero, so for example if the expectation of the drop is very close to 0 (like 0.25) and how does its distribute looks like? Or is it actually a chi-square distribution?

Thirdly, I found that many items have different lucky and non-lucky drops, without considering the generic lucky products (like XXX's sacks). For example, maple timber has a drop expectation of 16.5 for non-lucky and 18.5 for lucky, and chicken and eggs, which originally doubled when lucky was triggered.

But I noticed that you seem to have removed this aspect of lucky drops from the Plantzone page. Is it because luck is now useless except in the case of generic luck products(sacks)?

**Comment by shrddr** [comment]
1) binomial distribution is symmetrical only at p=0.5, try https://homepage.divms.uiowa.edu/~mbognar/applets/bin.html with n=140 & np=16.5 => p = 0.11785714285714285
2) play around using same link
3) the process of parameter fitting does not yield the one and only correct result, but a whole range of parameter combinations that are likely to be true. you can see on the scatterplot that the whole area around 16.5/16.5 is green (=likely to be true). 16.5/18.5 having the most p-value does not mean it is the real droprate. to confidently say parameters are NOT 16.5/16.5 you need to see a white point (= very low p-value) at 16.5/16.5 which is the case with chicken&eggs. i actually don't even look at Model C as long as Model A shows adequate results (see occam's razor)

**Comment by shrddr** [comment]
I think it's theoretically impossible to tell apart a mix of distributions with peaks at 16.5/18.5 and unknown variance from one slightly wider (=higher variance) distribution with peak at 17.5. So Model C is just overfitting in this case. Lucky and unlucky distributions must have a defined saddle between them to effectively tell them apart and infer the hidden parameters

**Comment by Leucothea** [comment]
Thanks for the answer, I understand it very clearly. But regarding some specific node like chicken and honey (not logging, farming, mining, digging, fishing node), their yields curve feel like they have a kind of another smaller "bell-shaped" uplift, like doubling their yields after triggering luck drop. I also feel like while I was actually counting. For most of the logging, mining and farming nodes, luck is not affected. But like chicken and honey nodes, luck seems to have an effect?

**Comment by shrddr** [comment]
All nodes with an icon of a box in a circle of arrows have luck affecting base material and none other nodes do (95% sure)
